- src/test/java/payload/Assignment.java
- src/test/java/tests/institution/assignmentmanagement/PostAssignmentTest.java
The test suite covers both positive and negative scenarios for creating assignments. Notable Changes:
- Included createAssignmentWithInvalidPhoneNumber() test case to verify the behavior when invalid phone numbers are provided.
These test cases ensure the correctness of the assignment creation process. Note that the mentioned test case may require updates in the future to adapt to any changes in the application's behavior regarding phone number validation.
> Added test cases for /api/v1/assignment endpoint

- src/test/java/endpoints/Authorization.java
- src/test/java/endpoints/InstitutionEndpoints.java
- src/test/java/endpoints/UserEndpoints.java
- src/test/java/tests/institution/assignmentmanagement/PostAssignmentTest.java
- src/test/java/tests/institution/assignmentmanagement/PostAssignmentsTest.java
- src/test/java/tests/user/UserAssignmentManagementServiceTest.java
- src/test/java/tests/user/UserLocationManagementServiceTest.java
- src/test/java/tests/user/UserSelfManagementServiceTest.java
Consolidated authorization logic into a single class for both users and institutions, streamlining the codebase. Additionally, updated endpoints and corresponding test classes to accommodate these changes.
> Refactor authorization handling for users and institutions

- src/test/java/logs/automation.log
- src/test/java/tests/auth/InstitutionAuthServiceTest.java
-Log details added for test cases IDs IAS_03, IAS_05, and IAS_06
> Add log details

- src/test/java/tests/user/UserSelfManagementServiceTest.java
-Implemented test case details via logger
-Refactored creation of user, instead of creating it in @BeforeClass setup Helper class is used
- UserSelfManagementServiceTest class structure refactored; DataProvider implemented
> Refactor UserSelfManagementServiceTest class

- src/test/java/payload/Helper.java
- src/test/java/payload/Pagination.java
- src/test/java/tests/institution/assignmentmanagement/DeleteAssignmentTest.java
- src/test/java/tests/institution/assignmentmanagement/GetAssignmentServiceTest.java
- src/test/java/tests/institution/assignmentmanagement/GetUpdateDeleteAssignmentTest.java
- src/test/java/tests/institution/assignmentmanagement/PostAssignmentsTest.java
- src/test/java/tests/institution/assignmentmanagement/UpdateAssignmentServiceTest.java
Added test case numbers are IAMS01-IAMS12
> Add automation test case scripts for /api/v1/assignments endpoints

- CODEOWNERS
Improvements to the GitHub Community Standards
Closes #[2]
Authorized persons in the Project were added and edited in the CODEOWNERS file.
> #2 - CODEOWNERS file edited.

- src/test/java/endpoints/Authorization.java
- src/test/java/endpoints/InstitutionEndpoints.java
- src/test/java/endpoints/Routes.java
- src/test/java/payload/FilterForInstitution.java
- src/test/java/payload/RequestBodyInstitution.java
- src/test/java/payload/Sort.java
- src/test/java/payload/SuperAdminCredentials.java
- src/test/java/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationsTest.java
post admin/registration-applications testi ile ilgili code lar eklendi
> PostAdminRegistrationApplicationsTest added

- pom.xml
- src/test/java/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationsTest.java
PostAdminRegistrationApplicationTest.java class ı na yeni test caseler eklendi
pom.xml dosyasındaki surfire plugin versiyon güncellenmesi yapıldı.
Hata veren testler için Jira'da bug issues'u açılıp (AYS-90) ready for development bölümüne taşındı. (Bu issue QA ekibi içindir)
> AYS-72 | New test cases added in PostAdminRegistrationApplicationsTest

- src/test/java/endpoints/InstitutionEndpoints.java
- src/test/java/tests/institution/adminregistrationmanagementservice/GetAdminRegistrationApplicationIDTest.java
institutionID bilgisi adminID ile değiştirildi.
createAnInstution method silindi.
> AYS-70 | GetRegistrationApplicationsId updated.

- .gitignore
- pom.xml
The Allure dependency was included in the pom.xml to leverage its annotations, enhancing the readability of test classes.
Closes #[AYS-92]
-The dependency for Allure was added
-Allure test result directory was specified in the .gitignore file.
N/A
[AYS-92]: https://afetyonetimsistemi.atlassian.net/browse/AYS-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allure dependency added to pom.xml

- src/test/java/tests/institution/adminmanagementservice/PostAdminsTest.java
Allure annotations are integrated into the Post Admins Test class
Closes #[AYS-102]
-Data provider methods have been added for positive and negative pagination scenarios.
-Allure annotations including @Epic, @Story, and @Severity have been incorporated to specify the test methods.
-Request specifications have been defined for positive and negative scenarios to avoid repetition of code lines.
None
None
[AYS-102]: https://afetyonetimsistemi.atlassian.net/browse/AYS-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allure annotations integration for PostAdminsTest.java class

- src/test/java/endpoints/InstitutionEndpoints.java
- src/test/java/payload/FiltersForUsers.java
- src/test/java/payload/Helper.java
- src/test/java/payload/RequestBodyUsers.java
- src/test/java/tests/institution/usermanagementservice/PostUsersTest.java
- src/test/java/utility/DataProvider.java
- src/test/java/utility/ExcelDataProvider.java
New test cases and allure annotations integration for /api/v1/users
- 42 test scenarios have been implemented for the /api/v1/users endpoint.
- A dedicated DataProvider class has been created, housing methods for supplying data to the test scenarios.
- Helper class now contains essential methods facilitating filtering and sorting operations.
- The RequestBodyUsers class has been introduced to encapsulate the request body structure for the /api/v1/users endpoint.
> Test cases added for /api/v1/users endpoints

- src/test/java/payload/Helper.java
- src/test/java/tests/institution/assignmentmanagementservice/PostAssignmentsTest.java
This commit contains 25 test scenarios for /api/v1/assignments endpoint
Closes #[AYS-94]
- Additional test cases have been included to enhance the filtering of assignments.
- These test cases includes both positive and negative scenarios, focusing on filtering based on phone numbers and pagination.
- The scope of these test cases is restricted to positive scenarios, specifically filtering assignments by status, line number, and country code. This limitation arises due to the absence of effective bug message management in the backend. Once the issue is addressed, these test cases will be updated accordingly.
- The Helper class has been extended with new methods to facilitate the creation of filtering assignments in the request body.
- …
> Test cases added for /api/v1/assignments endpoints

- src/test/java/tests/institution/assignmentmanagementservice/PostAssignmentTest.java
- src/test/java/utility/DataProvider.java
This PR includes changes for /api/v1/assignment endpoint
Closes #[AYS-109]
- Data provider methods moved to the DataProvider class for better organization.
- Allure annotations integrated  for enhanced test documentation.
- Spec specification implemented.
- Additional test scenarios added  to cover various inputs for first and last names.
[AYS-109]: https://afetyonetimsistemi.atlassian.net/browse/AYS-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Test cases refactored for /api/v1/assignment endpoint

- pom.xml
Rest Assured, Cucumber java, Java Faker kütüphanelerindeki güvenlik açıkları giderildi.
Alt kütüphanelerdeki conflict veren versiyonlar giderildi.
API otomasyonu için framework güvenliği tamamlandı.
>  AYS-89 | The security vulnerabilities in dependencies have been resolved.

- src/test/java/payload/Helper.java
- src/test/java/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationTest.java
- src/test/java/utility/DataProvider.java
Test case scripts added for /api/v1/admin/registration-application
Closes #[AYS-113]
-A new test class created for this endpoint
-Positive and negative test scenarios added to this class
-2 new methods added to the Helper class
-1 Data Provider method added to the DataProvider class
[AYS-113]: https://afetyonetimsistemi.atlassian.net/browse/AYS-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Test cases added for /api/v1/admin/registration-application

- pom.xml
- src/test/java/runners/ListenerSample.xml
- src/test/java/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationTest.java
Post Registration Application test class updated with new log file improvement
Closes #[AYS-114]
-An xml runner added 
-Weekly test runner updated with new xml runner in pom.xml
NA
NA
[AYS-114]: https://afetyonetimsistemi.atlassian.net/browse/AYS-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Test case log improvement

- src/test/java/tests/institution/usermanagementservice/PostUsersTest.java
Assertion of 'createdAt' field for '/api/v1/users'
Closes #[AYS-135]
-Added a new test method to validate all user details fields in the response.
-Refactored previous test cases specifically to validate the 'createdAt' field
-Deleted allure report related parts
NA
NA
[AYS-135]: https://afetyonetimsistemi.atlassian.net/browse/AYS-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-35|Assertion of 'createdAt' field for '/api/v1/users'

- src/test/java/tests/AysResponseSpecs.java
- src/test/java/tests/auth/InstitutionAuthServiceTest.java
- src/test/java/tests/auth/UserAuthServiceTest.java
Test for get access token with invalidated refresh token
Closes #[AYS-130]
-Test cases added for user and admin
NA
NA
[AYS-130]: https://afetyonetimsistemi.atlassian.net/browse/AYS-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-130|Test Invalid Refresh Token For Access Token Creation

- src/test/java/org/ays/endpoints/InstitutionEndpoints.java
- src/test/java/org/ays/payload/Helper.java
- src/test/java/org/ays/tests/institution/institutionservice/GetInstitutionsSummaryTest.java
- src/test/java/org/ays/utility/AysLogUtil.java
- src/test/resources/testsuite/RegressionSuite.xml
- src/test/resources/testsuite/SmokeSuite.xml
Test automation for institutions summary endpoint
Closes #[AYS-66]
-Test class created and a test method added
-2 new methods added to Helper class 
-Endpoint added to InstitutionEndpoints class
[AYS-66]: https://afetyonetimsistemi.atlassian.net/browse/AYS-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-66 | Test for institutions summary service

- src/test/java/org/ays/endpoints/InstitutionEndpoints.java
- src/test/java/org/ays/payload/ApplicationRegistrationSupportStatus.java
- src/test/java/org/ays/payload/Filter.java
- src/test/java/org/ays/payload/RegistrationApplicationCompletePayload.java
- src/test/java/org/ays/payload/RequestBodyForRegistrationIDComplete.java
- src/test/java/org/ays/payload/RequestBodyInstitution.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
- src/test/java/org/ays/utility/AysRandomUtil.java
- src/test/java/org/ays/utility/DataProvider.java
- `PostAdminRegistrationApplicationIDCompleteTest` class oluşturuldu.
- `COMPLETED` statüsüne sahip applicationID bilgisi için `InstitutionEndpoints` içerisine method oluşturuldu.
- `Filter` class a `generate` methodu eklendi.
- `ApplicationRegistrationSupportStatus` enum payload packgace altına eklendi.
- `RequestBodyInstitution` classına `generateFilter` methodu eklendi.
- `AysRandomUtil` classına `generateUsername, generateEmailAddress, generatePassword` methodları eklendi.
- `DataProvider` classına` invalidFirstAndLastNamesDataForAdminRegistration, invalidEmailForAdminRegistration, invalidPhoneNumberDataForRegistrationComplete` methodları eklendi.
> AYS-186 | `PostAdminRegistrationApplicationIDCompleteTest` added.

- src/test/java/org/ays/payload/AdminUserRegistrationApplicationStatus.java
- src/test/java/org/ays/payload/ApplicationStatus.java
- src/test/java/org/ays/payload/RejectReason.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/GetAdminRegistrationApplicationIdSummaryTest.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/GetAdminRegistrationApplicationTest.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationApproveTest.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationIDCompleteTest.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationRejectTest.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationTest.java
- src/test/java/org/ays/tests/institution/adminregistrationmanagementservice/PostAdminRegistrationApplicationsTest.java
- src/test/java/org/ays/tests/institution/usermanagementservice/DeleteUserTest.java
- src/test/java/org/ays/tests/institution/usermanagementservice/GetUserTest.java
- src/test/java/org/ays/tests/institution/usermanagementservice/PostUserTest.java
- src/test/java/org/ays/tests/institution/usermanagementservice/PutUserTest.java
- src/test/java/org/ays/tests/user/selfmanagementservice/GetUserSelfTest.java
- src/test/java/org/ays/utility/AysRandomUtil.java
- src/test/java/org/ays/utility/AysResponseSpecs.java
approval and rejection endpoints.
Provide a brief description of the changes in this pull request.
Closes #[AYS-193]
- Added positive scenarios for application rejection and approval.
- Removed HttpStatus from specifications and assertions.
- Deleted location and assignment-related code.
- Enabled previously failed test cases for future updates and raised corresponding Jira issues
- Applied AysResponseSpec classes to several classes.
[AYS-193]: https://afetyonetimsistemi.atlassian.net/browse/AYS-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> AYS-193 | Added positive scenarios for application

- src/test/java/org/ays/endpoints/LandingEndpoints.java
- src/test/java/org/ays/payload/EmergencyEvacuationApplication.java
- src/test/java/org/ays/tests/landing/emergencyevacuationapplyservice/PostEmergencyEvacuationApplicationTest.java
- src/test/java/org/ays/utility/AysRandomUtil.java
- src/test/java/org/ays/utility/DataProvider.java
- src/test/java/org/ays/utility/ErrorMessage.java
- src/test/resources/testsuite/RegressionSuite.xml
- src/test/resources/testsuite/SmokeSuite.xml
Added Emergency Evacuation Application automation tests
Closes #[221]
- LandingEndpoints Class Added
- Enum Class Added for Error Messages
- Post Emergency Evacuation Application Classes Added for api/v1/emergency-evacuation-application Endpoint
> AYS-221| Added Emergency Evacuation Application automation tests

- src/test/java/org/ays/endpoints/InstitutionEndpoints.java
- src/test/java/org/ays/payload/EmergencyEvacuationApplicationsFilter.java
- src/test/java/org/ays/payload/ListEmergencyEvacuationApplications.java
- src/test/java/org/ays/payload/Pageable.java
- src/test/java/org/ays/tests/institution/adminmanagementservice/PostAdminsTest.java
- src/test/java/org/ays/tests/institution/emergencyevacuationapplicationmanagementservice/PostEmergencyEvacuationApplicationsTest.java
- src/test/java/org/ays/tests/institution/usermanagementservice/PostUsersTest.java
- src/test/java/org/ays/tests/landing/emergencyevacuationapplyservice/PostEmergencyEvacuationApplicationTest.java
- src/test/java/org/ays/utility/AysResponseSpecs.java
- src/test/java/org/ays/utility/DataProvider.java
- src/test/java/org/ays/utility/DatabaseUtility.java
- src/test/java/org/ays/utility/ErrorMessage.java
- src/test/resources/testsuite/RegressionSuite.xml
- src/test/resources/testsuite/SmokeSuite.xml
Added List Emergency Evacuation Applications automation tests
Closes #[AYS-284]
List the changes you made in this pull request.
Added List Emergency Evacuation Applications automation tests
None
[AYS-284]: https://afetyonetimsistemi.atlassian.net/browse/AYS-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-284| Added List Emergency Evacuation Applications

- src/test/java/org/ays/endpoints/InstitutionAuthEndpoints.java
- src/test/java/org/ays/payload/PasswordForgotPayload.java
- src/test/java/org/ays/tests/auth/passwordManagement/PostPasswordForgotTest.java
- src/test/java/org/ays/utility/DataProvider.java
- src/test/java/org/ays/utility/DatabaseUtility.java
Şifremi Unuttum servisi pozitif ve negatif testleri eklendi
Closes #[AYS-341]
List the changes you made in this pull request.
[AYS-341]: https://afetyonetimsistemi.atlassian.net/browse/AYS-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-341 | Password Forgot Service

- src/test/java/org/ays/endpoints/InstitutionEndpoints.java
- src/test/java/org/ays/payload/RoleUpdatePayload.java
- src/test/java/org/ays/tests/institution/roleManagementService/PutRoleTest.java
- src/test/java/org/ays/utility/DataProvider.java
- src/test/java/org/ays/utility/DatabaseUtility.java
- src/test/resources/testsuite/InstitutionTestSuite.xml
- src/test/resources/testsuite/RegressionSuite.xml
- src/test/resources/testsuite/SmokeSuite.xml
Role Update Service Automation
Closes #[AYS-350]
Role Update positive scenario has been added.
Role Update negative scenarios have been added.
[AYS-350]: https://afetyonetimsistemi.atlassian.net/browse/AYS-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-350 | Role Update Service Automation

- src/test/java/org/ays/endpoints/InstitutionEndpoints.java
- src/test/java/org/ays/tests/institution/roleManagementService/DeleteRoleTest.java
- src/test/java/org/ays/utility/DataProvider.java
- src/test/java/org/ays/utility/DatabaseUtility.java
- src/test/resources/testsuite/InstitutionTestSuite.xml
- src/test/resources/testsuite/RegressionSuite.xml
- src/test/resources/testsuite/SmokeSuite.xml
Role deleting service tests have been added.
Closes #[AYS-371]
Role deleting service positive and negative tests have been added.
[AYS-371]: https://afetyonetimsistemi.atlassian.net/browse/AYS-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-371 | Role Deleting Service Automation

- pom.xml
Dependencies Versions Have Been Updated.
Closes #[AYS-291]
pom.xml
[AYS-291]: https://afetyonetimsistemi.atlassian.net/browse/AYS-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-291 | Updating Dependency Versions

- src/test/java/org/ays/common/model/enums/AysErrorMessage.java
- src/test/java/org/ays/common/util/AysDataProvider.java
- src/test/java/org/ays/common/util/AysRandomUtil.java
- src/test/java/org/ays/common/util/AysResponseSpecs.java
- src/test/java/org/ays/emergencyapplication/tests/EmergencyEvacuationApplicationsListTest.java
- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationsListTest.java
pageSize error messages have been changed.
Closes #[AYS-495]
Changed DataProvider pageable methods
[AYS-495]: https://afetyonetimsistemi.atlassian.net/browse/AYS-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AYS-495 | Page Size Error Message Change

- CODEOWNERS
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
Provide a brief description of the changes in this pull request.
Closes #[Issue Number]
List the changes you made in this pull request.
> AYS-522| Refactor PR template

- src/test/java/org/ays/common/util/AysResponseSpecs.java
Added returning `code` field in response..
AysResponseSpecs class edited.
.
.
- …
> AYS-510 | Response Specification Editing

- src/test/java/org/ays/auth/datasource/PermissionDataSource.java
- src/test/java/org/ays/auth/datasource/RoleDataSource.java
- src/test/java/org/ays/auth/tests/RoleCreateTest.java
- src/test/java/org/ays/common/util/AysDataProvider.java
- Positive and negative tests have been added for role creation.
- Added positive and negative tests for role creation functionality in RoleCreateTest.
- Added findLastCreatedRoleNameByInstitutionId method in RoleDataSource to get the last created role's name.
- Added findLastCreatedRoleStatusByInstitutionId method in RoleDataSource to get the last created role's status.
- Added getPermissionIdsFromLastCreatedRole method in PermissionDataSource to fetch the permission IDs of the last created role.
Before submitting your pull request, ensure …
> AYS-278 | Added positive and negative tests for role creation functionality

- src/test/java/org/ays/auth/tests/PasswordForgotTest.java
- src/test/java/org/ays/common/util/AysResponseSpecs.java
Added tests for existence and change of 'time' field
Added tests for existence and change of 'time' field
.
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/blob/main/CONTRIBUTING.md …
> AYS-559 | Test 'time' Field Change in Response

- src/test/java/org/ays/common/util/AysDataProvider.java
- src/test/java/org/ays/emergencyapplication/model/enums/EmergencyEvacuationApplicationStatus.java
- src/test/java/org/ays/emergencyapplication/tests/EmergencyEvacuationApplicationsListTest.java
EmergencyEvacuationApplicationsList response body edited.
`applicantFirstName`, `applicantLastName`, `applicantPhoneNumber` information has been added to the fields returned in response.
New test case added for existing not `isInPerson` application
.
- The branch name follows one of the …
> AYS-420 | Refactor EmergencyEvacuationApplicationsList Response Body 

- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationCompleteTest.java
New test cases have been added in AdminRegistrationApplicationCompleteTest class.
Complete process verification tests have been added with IDs with rejected and approved statuses.
.
the [Branch Naming …
> AYS-465 | Adding New Test Cases for Complete Service

- src/test/java/org/ays/auth/tests/RoleCreateTest.java
- src/test/java/org/ays/common/model/enums/AysErrorMessage.java
- src/test/java/org/ays/common/util/AysDataProvider.java
- src/test/resources/testsuite/RegressionSuite.xml
- src/test/resources/testsuite/SmokeSuite.xml
New test data have been added for `emailAddress`
Added new error message in AysErrorMesage enum
Added new data in `invalidEmailAddress` data provider method
Refactored some error message in `invalidEmailAddress` data provider method
.
- The branch name follows one of the conventions …
> AYS-551 | Add New Test Data for Email Address

- src/test/java/org/ays/common/util/AysResponseSpecs.java
Update 409 error message assertions as CONFLICT ERROR
Assertion updated from spec class
None
None
.
.
- All tests are passing.
- I tagged all test as smoke or regression
- …
> AYS-555 | Update 409 error message assertions

- src/test/java/org/ays/common/util/AysRandomUtil.java
.
.
- All tests are passing.
- I tagged all test as smoke or regression
- I added newly added tests to related xml file in test suite
- The code is formatted according to the project's coding guidelines and style.
- The code has been reviewed to ensure its …
> AYS-624 | `AysRandomUtil.generateEmailAddress()` Method Has Been Refactored with Custom Domain Name

- src/test/java/org/ays/auth/datasource/PermissionDataSource.java
- src/test/java/org/ays/auth/model/enums/Permission.java
- src/test/java/org/ays/auth/model/enums/PermissionCategory.java
- src/test/java/org/ays/auth/payload/RoleCreatePayload.java
- src/test/java/org/ays/auth/tests/PasswordForgotTest.java
- src/test/java/org/ays/auth/tests/RoleCreateTest.java
Forgot password tests refactored  to cover permission validations. 
-New tests added
-Previous tests refactored according to new validations.
None
I’d appreciate it if you could consider these points when reviewing. 
1.Are the method names findRandomPermissionIdsAsRoleManagementCategory() and findRandomPermissionIdsAsPageCategory() appropriate? Could they be merged into a single method and managed from the class level? I’d like your opinion on this.
2.When defining permissions, I am unsure whether to continue using the existing permission category PAGE (defining both landing and institution page permissions together) or to create a new enum class for PermissionName and define specific permissions …
> AYS-569 | Refactor PasswordForgotTest with permission validation

- src/test/java/org/ays/common/util/AysResponseSpecs.java
Deleted UpdatedAt field from list users response
Deleted UpdatedAt field from list users response
None
None
.
.
- All tests are passing.
- I tagged all test as smoke or …
> AYS-506 | Deleted UpdatedAt field from the list users response

- src/test/java/org/ays/auth/tests/PasswordForgotTest.java
- src/test/java/org/ays/auth/tests/TokenTest.java
- src/test/java/org/ays/auth/tests/UserCreateTest.java
- src/test/java/org/ays/auth/tests/UserUpdateTest.java
- src/test/java/org/ays/common/model/enums/AysErrorMessage.java
- src/test/java/org/ays/common/util/AysDataProvider.java
- src/test/java/org/ays/common/util/AysRandomUtil.java
- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationCompleteTest.java
- Added password length validation tests for minimum and maximum length passwords.
- TokenTest Class: Added password length validation and edge case tests. Introduced a new invalidPasswordAndEdgeCases DataProvider to test various invalid password cases, such as blank, passwords less than 8 characters, and greater than 128 characters.
- AysErrorMessage: Added a new error message for password validation related to the length constraint.
- AysRandomUtil: Added a generatePasswordWithinRange method to help generate passwords of varying lengths for testing edge cases.
Provide instructions or guidelines for reviewers to follow when …
> AYS-614 | Password Length Validation

- src/test/java/org/ays/auth/tests/PasswordForgotTest.java
- src/test/java/org/ays/auth/tests/TokenTest.java
- src/test/java/org/ays/auth/tests/UserCreateTest.java
- src/test/java/org/ays/auth/tests/UserUpdateTest.java
- src/test/java/org/ays/common/model/enums/AysErrorMessage.java
- src/test/java/org/ays/common/util/AysDataProvider.java
- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationCompleteTest.java
Email Address Validation Error Messages Has Been Refactored
- Updated e-mail validation error messages to 'MUST_BE_VALID' for specific cases.
- Removed 'enable = false' tags after fixing the tests.
.
the [Branch Naming …
> AYS-674 | Email Address Validation Error Messages Has Been Refactored

- src/test/java/org/ays/common/model/enums/AysErrorMessage.java
- src/test/java/org/ays/emergencyapplication/tests/EmergencyEvacuationApplicationCreateTest.java
Add New Tests For The Same Source and Target Location 
testSameSourceAndTargetLocationForMe test has been added.
testSameSourceAndTargetLocationForOtherPerson test has been added.
New error message has been added.
.
the …
> AYS-602 | Add New Tests For The Same Source and Target Location 

- src/test/java/org/ays/common/util/AysResponseSpecs.java
Error message has been refactored.
`NOT EXIST` error messages refactor to `NOT EXIST ERROR`
.
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/blob/main/CONTRIBUTING.md#branch-naming …
> AYS-683 | Error Message Refactor

- src/test/java/org/ays/common/util/AysRandomUtil.java
generateEmailAddress method has been refactored.
generateEmailAddress method has been refactored.
.
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/blob/main/CONTRIBUTING.md#branch- …
> AYS-698 | Refactore Email Address Method

- pom.xml
- src/test/java/org/ays/auth/datasource/UserDataSource.java
- src/test/java/org/ays/auth/tests/TokenTest.java
- src/test/java/org/ays/auth/tests/UsersListTest.java
- All tests are passing.
- I tagged all test as smoke or regression
- I added newly added tests to related xml file in test suite
- The code is formatted according to the project's coding guidelines and style.
- The code has been reviewed to ensure its quality. …
> AYS-657 | All Dependencies Have Been Upgraded to Latest Version and Vulnerabilities Have Been Fixed

- .github/workflows/pull-request-checker.yml
Update PR Checker to Prevent Extra Triggers in GitHub Workflow
Updated PR Checker yaml file to Prevent Extra Triggers in GitHub Workflow
.
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-autom …
> AYS-792 | Update PR Checker to Prevent Extra Triggers in GitHub Workflow

- CODE_OF_CONDUCT.md
- LICENSE.MD
- SECURITY.md
Updated License, code of conduct and security documentations with New Domain
Updated License, code of conduct and security documentations with New Domain
.
the [Branch Naming …
> AYS-783 | Update License Documentation with New Domain

- src/test/java/org/ays/auth/tests/RoleCreateTest.java
- src/test/java/org/ays/auth/tests/TokenInvalidateTest.java
- src/test/java/org/ays/auth/tests/TokenRefreshTest.java
- src/test/java/org/ays/auth/tests/TokenTest.java
- src/test/java/org/ays/common/model/enums/AysErrorMessage.java
- src/test/java/org/ays/common/util/AysDataProvider.java
- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationCompleteTest.java
Updated phone number error messages and enabled failed tests to be addressed in related issues
Updated phone number error messages and enabled failed tests to be addressed in related issues
Updated phone number error messages
Enabled failed tests
Removed unused data provider methods
none
none
.
the [Branch Naming Conventions](https://github.com/afet-yonetim-sistemi/ays-be-api-automatio …
> AYS-644 | Updated phone number error messages

- src/test/java/org/ays/common/util/AysRandomUtil.java
- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationCompleteTest.java
Phone number already exists error message is updated
- Re-enabled previously failing test
- Updated assertion logic to match the new masked phone number error message format
none
none
.
.
- I have added positive and negative test scenarios …
> AYS-785 | Update phone number already exists error message

- src/test/java/org/ays/auth/tests/RoleCreateTest.java
- src/test/java/org/ays/auth/tests/TokenInvalidateTest.java
- src/test/java/org/ays/auth/tests/TokenRefreshTest.java
- src/test/java/org/ays/auth/tests/TokenTest.java
- src/test/java/org/ays/registrationapplication/tests/AdminRegistrationApplicationCompleteTest.java
Update e-mail address already exists error message
-updated error message format for e-mail address
-enabled previously disabled tests
none
none
.
.
- All tests are …
> AYS-786 | Update e-mail address already exists error message
